Feature/430 add stacking of charts for user selected charts
akvo/wai-sdg-portal pull request #431
Opened 2023-10-11 11:09 UTC by wayangalihpratama

TODO / DONE

---

- #430 
- [x] Remove parameter chartFeature.stack from the config.js, modify the frontend so everybody can have this feature 
- [x] Append Administration to second/stack question dropdown 
  - But still using the question name
- [x] Make the bar charts vertical, otherwise, we have long list of administration
- [x] Modify agregated chart data route to support query by stack administration question
- [x] Transform stack bar into split bar chart
- [x] Add checkbox on the right corner says: show empty value and filter chart data value
- [x] Add checkbox into Chart component, but the state and data filtering happening on host/page using the chart component

2023-10-11 12:32 UTC, dedenbangkit commented
hi Galih, 21 files changed? is it true or you pushed different code format?

2023-10-11 23:46 UTC, wayangalihpratama commented
> hi Galih, 21 files changed? is it true or you pushed different code format?

Yes, 21 files changes, 
When remove the chartFeature from config we change 5 files (all instances).
Then when add checkbox, I add the "Show empty chart value" to i18n.js config (all instances, 5 files).
That's already 10 files. The other files related to backend, fe, and echarts components.

2023-10-12 02:52 UTC, dedenbangkit requested changes
![wai-split-chart-visualisation-too-tight](https://github.com/akvo/wai-sdg-portal/assets/3245109/3278ca13-59c8-491a-b257-6c024b85d448)

2023-10-12 06:13 UTC, dedenbangkit approved these changes

2023-10-12 06:13 UTC, merged